ente_appartenenza: 'Universit√† degli Studi di Cagliari'
_core:
  default_config_hash: sUXbAWjCCUm114hgcUWPGMzCwtGxUBY_DWXKsEH6JZ4
langcode: it
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
