geocoder_presave_disabled: false
cache: true
plugins_options:
  arcgisonline:
    sourcecountry: ''
    usessl: false
  bingmaps:
    apikey: ''
    locale: ''
  geonames:
    username: ''
    locale: ''
  googlemaps:
    apikey: AIzaSyAVfT_5OET3Qd3B0t8kAuSZoNor2_h3wtM
    locale: ''
    region: ''
    usessl: true
  googlemaps_business:
    clientId: ''
    privateKey: ''
    locale: ''
    region: ''
    usessl: true
  ipinfodb:
    apikey: ''
    precision: city
  mapquest:
    apikey: ''
    licensed: false
  maxmind:
    apikey: ''
    service: f
    usessl: false
  nominatim:
    rooturl: ''
    locale: ''
  opencage:
    apikey: ''
    locale: ''
    usessl: false
  tomtom:
    apikey: ''
    locale: ''
  file: {  }
  freegeoip: {  }
  geoip: {  }
  geojsonfile: {  }
  geoplugin: {  }
  gpxfile: {  }
  hostip: {  }
  kmlfile: {  }
  openstreetmap: {  }
  random: {  }
  yandex: {  }
_core:
  default_config_hash: Q3XGbAMJGjcXv448RHIkNVdJvsPs44db4LjOVp3z-LI
langcode: it
